### ISSUE TITLE
RaFD

### ISSUE THREAD

**Issue by BodeJia** [justin941208/MatchGAN#7]
I can't open the download link of the RaFD dataset, could you please take time out of your busy schedule to send a copy to my email? Much appreciated. 
jiabode@stu.ouc.edu.cn
![image](https://github.com/justin941208/MatchGAN/assets/141536532/764b0375-3c43-458c-949f-9a686a9ae575)

**Comment by justin941208** [comment]
The old link stopped working for some reason, but I have updated the README file with the new link. It should be working now.

I'm afraid I wouldn't be able to send the data directly to you as access to the dataset requires permission. Perhaps you could send a request directly through the website and they should get back to you.
